# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'gadslh'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'name of your profile file'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  gadslh:
    production: 
      materialized: table
    staging:
      materialized: ephemeral

vars: 
  t_campaignStats: 'dashboard-419810.google_ads.p_ads_CampaignStats_1369664160'
  t_campaign: 'dashboard-419810.google_ads.p_ads_Campaign_1369664160'
  t_ads: 'dashboard-419810.google_ads.p_ads_Ad_1369664160'
  t_adStats: 'dashboard-419810.google_ads.p_ads_AdStats_1369664160'
  t_campaignConv: 'dashboard-419810.google_ads.p_ads_CampaignConversionStats_1369664160'
  t_adGroupStats: 'dashboard-419810.google_ads.p_ads_AdGroupStats_1369664160'
  t_adGroup: 'dashboard-419810.google_ads.p_ads_AdGroup_1369664160'
  t_adGroupConv: 'dashboard-419810.google_ads.p_ads_AdGroupConversionStats_1369664160'
  convName1: 'ENGAGEMENT'
  convName2: 'PURCHASE'
  convName3: 'name of third conversion'
